name: Release
on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: ${{ matrix.os }} release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: binlink
            asset_name: binlink-linux-amd64
          - os: macos-latest
            artifact_name: binlink
            asset_name: binlink-macos-amd64

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --release
      - name: Archive Release
        uses: papeloto/action-zip@v1
        with:
          files: target/release/binlink
          recursive: false
          dest: target/${{ matrix.asset_name }}.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.asset_name }}.zip
          asset_name: ${{ matrix.asset_name }}.zip
          tag: ${{ github.ref }}
      - uses: mislav/bump-homebrew-formula-action@v1
        if: ${{ matrix.os == "macos-latest" }}
        with:
          formula-name: binlink
          homebrew-tap: 7mind/homebrew-tools
          base-branch: master
          commit-message: "{{formulaName}} {{version}}"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
